dist: xenial
sudo: false
language: python
python:
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install requests --upgrade
  - pip install websockets --upgrade
  - pip install pyyaml
script:
  - pip freeze
  - python setup.py test
